# https://github.com/timvancann/yt-python-ci/blob/main/.github/actions/setup/action.yml
runs:
  using: composite
  steps:
    - name: "Install UV"
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
