"""CODE V File Encoder

Converts a CodeVDataModel into a list of .seq text lines in the order and
format expected by CODE V. The encoded lines are written to disk as UTF-8.

Kramer Harrison, 2026
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from optiland.fileio.codev.model import CodeVDataModel

# Ordered aspheric coefficient letter keys (4th–20th order)
_ASPH_KEYS = ("A", "B", "C", "D", "E", "F", "G", "H", "J")

# Map from field type string to (x-command, y-command) pair
_FIELD_TYPE_CMDS: dict[str, tuple[str, str]] = {
    "angle": ("XAN", "YAN"),
    "object_height": ("XOB", "YOB"),
    "paraxial_image_height": ("XIM", "YIM"),
    "real_image_height": ("XIM", "YIM"),
}

# Map from CODE V aperture key to command string
_AP_KEY_TO_CMD: dict[str, str] = {
    "EPD": "EPD",
    "FNO": "FNO",
    "NA": "NA",
    "NAO": "NAO",
}


def _fmt(value: float) -> str:
    """Format a float compactly without unnecessary trailing zeros.

    Args:
        value: The float to format.

    Returns:
        A compact string representation.
    """
    return f"{value:.8g}"


def _fmt_list(values: list[float]) -> str:
    """Format a list of floats separated by spaces.

    Args:
        values: List of floats to format.

    Returns:
        Space-separated string of formatted values.
    """
    return " ".join(_fmt(v) for v in values)


class CodeVFileEncoder:
    """Encodes a CodeVDataModel as a list of .seq text lines.

    Args:
        model: The CodeVDataModel to encode.
    """

    def __init__(self, model: CodeVDataModel):
        self._model = model

    def encode(self) -> list[str]:
        """Produce the complete list of .seq text lines.

        Returns:
            A list of strings, one per line of the output file.
        """
        lines: list[str] = []
        self._encode_header(lines)
        self._encode_surfaces(lines)
        return lines

    # ------------------------------------------------------------------
    # Header block
    # ------------------------------------------------------------------

    def _encode_header(self, lines: list[str]) -> None:
        lines.append("! Generated by Optiland")
        lines.append("RDM Y")
        if self._model.name:
            lines.append(f"TITLE '{self._model.name}'")
        self._encode_aperture(lines)
        self._encode_wavelengths(lines)
        self._encode_fields(lines)
        lines.append("")  # blank separator before surfaces

    def _encode_aperture(self, lines: list[str]) -> None:
        ap = self._model.aperture
        if not ap:
            return
        for key, cmd in _AP_KEY_TO_CMD.items():
            if key in ap:
                lines.append(f"{cmd} {_fmt(ap[key])}")
                return

    def _encode_wavelengths(self, lines: list[str]) -> None:
        wl_data = self._model.wavelengths
        data = wl_data.get("data", [])
        if not data:
            return
        # Convert µm → nm
        nm_values = [v * 1000.0 for v in data]
        lines.append("WL " + _fmt_list(nm_values))

        weights = wl_data.get("weights")
        if weights:
            lines.append("WTW " + _fmt_list(weights))
        else:
            lines.append("WTW " + " ".join(["1"] * len(data)))

        primary_index = wl_data.get("primary_index", 0)
        lines.append(f"REF {primary_index + 1}")

    def _encode_fields(self, lines: list[str]) -> None:
        fields = self._model.fields
        field_type = fields.get("type", "angle")
        x_vals = fields.get("x", [])
        y_vals = fields.get("y", [])
        if not y_vals:
            return

        x_cmd, y_cmd = _FIELD_TYPE_CMDS.get(field_type, ("XAN", "YAN"))

        if x_vals and any(abs(v) > 1e-12 for v in x_vals):
            lines.append(f"{x_cmd} " + _fmt_list(x_vals))
        lines.append(f"{y_cmd} " + _fmt_list(y_vals))

        weights = fields.get("weights")
        if weights and any(abs(w - 1.0) > 1e-12 for w in weights):
            lines.append("WTF " + _fmt_list(weights))

    # ------------------------------------------------------------------
    # Surface blocks
    # ------------------------------------------------------------------

    def _encode_surfaces(self, lines: list[str]) -> None:
        for idx in sorted(self._model.surfaces.keys()):
            raw = self._model.surfaces[idx]
            self._encode_surface(lines, raw)

    def _encode_surface(self, lines: list[str], raw: dict[str, Any]) -> None:
        surf_type = raw.get("type", "standard")
        radius = raw.get("radius", 0.0)
        thickness = raw.get("thickness", 0.0)
        glass = raw.get("glass")

        r_str = _fmt(float(radius))
        t_str = _fmt(float(thickness))

        if surf_type == "object":
            line = f"SO {r_str} {t_str}"
        elif surf_type == "image":
            line = f"SI {r_str} {t_str}"
        else:
            glass_str = self._encode_glass_inline(glass) if glass else ""
            line = f"S  {r_str} {t_str}"
            if glass_str:
                line += f"  {glass_str}"

        lines.append(line)

        # Surface modifiers (indented for readability)
        if raw.get("is_stop"):
            lines.append("  STO")

        conic = raw.get("conic", 0.0)
        if conic is not None and abs(float(conic)) > 1e-16:
            lines.append(f"  K {_fmt(float(conic))}")

        # Aspheric coefficients
        profile = raw.get("profile", "SPH")
        if profile == "ASP":
            for i, key in enumerate(_ASPH_KEYS):
                val = float(raw.get(f"coeff_{i}", 0.0))
                if abs(val) > 1e-30:
                    lines.append(f"  {key} {_fmt(val)}")

        # Decenters and tilts
        for cv_key, label in (
            ("xde", "XDE"),
            ("yde", "YDE"),
            ("zde", "ZDE"),
            ("ade", "ADE"),
            ("bde", "BDE"),
            ("cde", "CDE"),
        ):
            val = float(raw.get(cv_key, 0.0))
            if abs(val) > 1e-12:
                lines.append(f"  {label} {_fmt(val)}")

        # Physical aperture
        aperture = raw.get("aperture")
        if aperture is not None:
            try:
                r_max = float(aperture.r_max)
                lines.append(f"  CIR CLR {_fmt(r_max)}")
            except AttributeError:
                pass

    def _encode_glass_inline(self, glass: dict[str, Any]) -> str:
        """Build the glass string for the surface line.

        Args:
            glass: Glass specification dict from the formatter.

        Returns:
            Glass token string, e.g. ``"N-BK7_SCHOTT"`` or ``"1.5168:64.17"``.
        """
        name = glass.get("name", "")

        if name == "REFL":
            return "REFL"

        if "nd" in glass and "vd" in glass:
            # Fictitious glass: Nd:Vd format
            nd = glass["nd"]
            vd = glass["vd"]
            return f"{nd:.6f}:{vd:.4f}"

        catalog = glass.get("catalog")
        if catalog:
            return f"{name}_{catalog}"
        return name

    def _encode_glass_comment(self, glass: dict[str, Any]) -> str | None:
        """Return an optional comment string for a glass.

        Args:
            glass: Glass specification dict.

        Returns:
            A comment string or None.
        """
        if not glass:
            return None
        if "nd" in glass and "vd" in glass:
            return f"! Fictitious glass: Nd={glass['nd']:.6f}, Vd={glass['vd']:.2f}"
        return None
