"""
PDF Export Module for Optiland Reporting.

This module provides a rendering engine to compile reports into a single,
clean paginated PDF using matplotlib's backend_pdf.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Any

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

if TYPE_CHECKING:
    from matplotlib.figure import Figure


class PDFReportRenderer:
    """Renders reports to PDF."""

    def __init__(self, filename: str):
        self.filename = filename
        self.pdf = PdfPages(filename)
        self.page_number = 1

    def add_figure(self, fig: Figure, add_header_footer: bool = True):
        """Adds a matplotlib figure to the PDF."""
        if add_header_footer:
            self._add_header_footer(fig)
        self.pdf.savefig(fig, bbox_inches="tight")
        self.page_number += 1

    def _add_header_footer(self, fig: Figure):
        """Adds standard header and footer to the figure."""
        # Footer
        footer_text = (
            f"Generated by Optiland | "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M')} | Page {self.page_number}"
        )
        fig.text(
            0.5,
            0.02,
            footer_text,
            ha="center",
            va="bottom",
            fontsize=8,
            color="gray",
            fontfamily="sans-serif",
        )

    def render_table(
        self, data: list[list[Any]], col_labels: list[str], title: str = ""
    ) -> Figure:
        """Renders a data table as a matplotlib figure.

        Args:
            data: 2D list of data values.
            col_labels: List of column headers.
            title: Table title.

        Returns:
            A Figure object containing the rendered table.
        """
        # Calculate dynamic height based on number of rows
        # Base height for header + title + footer + margins
        row_height = 0.3
        base_height = 2.0
        est_height = base_height + (len(data) * row_height)

        # Cap min/max height
        fig_height = max(5, min(est_height, 11))

        fig, ax = plt.subplots(figsize=(8.5, fig_height))  # Portrait width
        ax.axis("tight")
        ax.axis("off")

        if title:
            ax.set_title(title, fontsize=14, weight="bold", pad=20)

        # Create table
        table = ax.table(
            cellText=data,
            colLabels=col_labels,
            loc="center",
            cellLoc="left",
            colLoc="left",
            edges="horizontal",
        )

        # Style the table
        table.auto_set_font_size(False)
        table.set_fontsize(9)
        table.scale(1, 1.8)  # More vertical padding

        # Styling loop
        for (row, _col), cell in table.get_celld().items():
            cell.set_edgecolor("#d0d0d0")
            cell.set_linewidth(0.5)

            if row == 0:
                cell.set_text_props(weight="bold", color="white")
                cell.set_facecolor("#2c3e50")  # Dark blue-grey header
                cell.set_edgecolor("#2c3e50")
            else:
                if row % 2 == 1:
                    cell.set_facecolor("#f8f9fa")  # Very light grey alternating
                else:
                    cell.set_facecolor("white")

        return fig

    def close(self):
        """Closes the PDF file."""
        self.pdf.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
