"""Field Solvers Module

This module contains classes for solving object-space field values
(e.g., height or angle) corresponding to a desired image-space height.

Kramer Harrison, 2025
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import optiland.backend as be
from optiland.fields.field_modes import AngleFieldMode, ObjectHeightFieldMode
from optiland.raytrace.paraxial_ray_tracer import (
    ParaxialRayTracer as BaseParaxialRayTracer,
)

if TYPE_CHECKING:
    from optiland.fields.field import Field
    from optiland.fields.field_modes import BaseFieldMode
    from optiland.optic import Optic


class ParaxialImageHeightSolver:
    """Solve image-height-defined fields into canonical object-side fields.

    The mapping from object-side field to paraxial image height is linear
    in a first-order model. This solver computes the proportionality
    constant by tracing one paraxial chief ray for a unit field,
    then scales to the requested target image height.
    """

    _unit_field_angle_deg_default: float = 1.0
    _unit_field_height_default: float = 1.0
    _rev_trace_seed_u: float = 0.1  # small slope for reverse trace seed

    def __init__(self) -> None:
        # Future knobs can be added here, for example:
        # self._cache_enabled = True
        # self._fallback_numeric = True
        pass

    def solve(self, optic: Optic, field: Field) -> tuple[str, float]:
        """Resolve an image-height field into a canonical object-side field.

        Args:
            optic: The optical system. Must expose paraxial tracing API.
            field: The field descriptor. Must carry the target paraxial
                image height in `field.value`. If your real Field carries
                image height under another name, adapt below.  # placeholder

        Returns:
            (mode_type, field_value):
                mode_type is "angle" for object at infinity,
                "object_height" otherwise.
                field_value is the canonical field value that produces
                the requested paraxial image height.

        Raises:
            ValueError: If a computed unit-field image height is zero or invalid.
        """
        target_image_height = float(
            field.value
        )  # placeholder: assumes field.value stores image height

        # Decide canonical mode based on object distance
        mode_type = "angle" if optic.object_surface.is_infinite else "object_height"

        # Compute image height at the image plane for a unit canonical field
        unit_image_height = self._image_height_for_unit_field(optic, mode_type)

        if be.isclose(unit_image_height, 0.0):
            raise ValueError(
                "Unit field produced zero paraxial image height, cannot solve. "
                "Check system stop definition and base mode chief-ray setup."
            )

        solved_value = target_image_height / unit_image_height
        return mode_type, solved_value

    def _image_height_for_unit_field(self, optic: Optic, mode_type: str) -> float:
        """Compute paraxial image height generated by a unit canonical field.

        The method derives a starting slope u1 at the stop corresponding to
        a unit canonical field using the base mode strategy, reverse traces
        to the object side reference plane, then forward traces to the image.

        Args:
            optic: The optical system.
            mode_type: "angle" or "object_height".

        Returns:
            Image height at the image plane for a unit canonical field.
        """
        # 1) Reverse trace a small slope ray from the stop center to get a
        #    reference state for chief ray setup.
        stop_idx, z_positions = self._stop_and_positions(optic)
        wavelength = float(optic.primary_wavelength)
        tracer = self._paraxial_tracer(optic)

        # Reverse trace start z is distance from stop to image plane reference.
        # Exact z convention is unknown. We replicate the user's earlier pattern.
        # # placeholder
        z0_rev = z_positions[-1] - z_positions[stop_idx]
        num_surfaces = len(z_positions)
        skip = num_surfaces - stop_idx

        y_rev, u_rev = tracer.trace_generic(
            y=0.0,
            u=self._rev_trace_seed_u,
            z=z0_rev,
            wavelength=wavelength,
            reverse=True,
            skip=skip,
        )
        y_at_initial = self._last(y_rev)
        u_at_initial = self._last(u_rev)

        # 2) Ask the canonical base mode for u1 per unit field at the stop.
        base_mode = self._base_mode_for(mode_type)
        u1_per_unit = self._chief_u1_per_unit(
            base_mode=base_mode,
            optic=optic,
            chief_ray_y_at_stop=y_at_initial,
            chief_ray_u_at_stop=u_at_initial,
            mode_type=mode_type,
        )

        # 3) Reverse trace from the stop with u1 for a unit field to get
        #    the object-side start conditions for forward trace.
        y_rev_unit, u_rev_unit = tracer.trace_generic(
            y=0.0,
            u=u1_per_unit,
            z=z0_rev,
            wavelength=wavelength,
            reverse=True,
            skip=skip,
        )

        # 4) Forward trace from the first optical surface to the image.
        #    Use the reversed endpoint as the object-side initial conditions.
        z0_fwd = z_positions[1]  # first optical surface global z  # placeholder
        y0 = -self._last(
            y_rev_unit
        )  # sign convention matches prior code  # placeholder
        u0 = self._last(u_rev_unit)

        y_fwd, _ = tracer.trace_generic(y=y0, u=u0, z=z0_fwd, wavelength=wavelength)

        return float(self._last(y_fwd))

    def _chief_u1_per_unit(
        self,
        base_mode: BaseFieldMode,
        optic: Optic,
        chief_ray_y_at_stop: float,
        chief_ray_u_at_stop: float,
        mode_type: str,
    ) -> float:
        """Compute the starting slope u1 at the stop per unit canonical field.

        Preferred path:
            Use the base mode's strategy method if it returns a slope that is
            already normalized to "per unit field". If your current
            implementation returns a slope for the system's max field, we
            normalize it to unit field via a known scale.

        Fallback path:
            Use a deterministic small-signal normalization that does not rely
            on system max field. This avoids magic factors and makes the solver
            independent of gallery settings.

        Args:
            base_mode: Instance of AngleFieldMode or ObjectHeightFieldMode.
            optic: Optical system.
            chief_ray_y_at_stop: y at the stop after seed reverse trace.
            chief_ray_u_at_stop: u at the stop after seed reverse trace.
            mode_type: "angle" or "object_height".

        Returns:
            u1 slope per unit canonical field at the stop.
        """
        # Try the mode's official method. Your current code uses a 0.1 factor
        # and system max field. We strip that dependency and normalize to unit.
        try:
            u1_raw = base_mode.get_chief_ray_start_params(
                optic, chief_ray_y_at_stop, chief_ray_u_at_stop
            )
        except Exception:
            u1_raw = None

        if u1_raw is not None:
            # Heuristic normalization to unit field:
            # If mode uses max_y_field inside, divide by that to get per unit.
            # Otherwise, this acts as a no-op. # TODO
            max_field = getattr(optic.fields, "max_y_field", None)  # placeholder
            if isinstance(max_field, int | float) and max_field not in (0, None):
                return float(u1_raw) / float(max_field)
            return float(u1_raw)

        # Fallback numeric small-signal mapping:
        # Pick a tiny canonical field delta and derive u1 via proportionality.
        if mode_type == "angle":
            unit = be.deg2rad(self._unit_field_angle_deg_default)
        else:
            unit = self._unit_field_height_default

        # For small fields, chief slope scales approximately linearly.
        # Use a fixed proportionality between u at stop and field unit, tied to geometry
        eps = 1e-6
        scale = unit / max(abs(chief_ray_y_at_stop) + eps, eps)
        return float(scale)

    @staticmethod
    def _paraxial_tracer(optic: Optic) -> BaseParaxialRayTracer:
        """Construct a paraxial tracer for the given optic."""
        return BaseParaxialRayTracer(optic)

    @staticmethod
    def _stop_and_positions(optic: Optic) -> tuple[int, Any]:
        """Return stop index and global z positions array."""
        sg = optic.surface_group
        return int(sg.stop_index), sg.positions

    @staticmethod
    def _base_mode_for(mode_type: str) -> BaseFieldMode:
        """Instantiate a canonical mode instance with a trivial group.

        The solver never iterates fields through this instance. It only uses
        chief-ray setup logic that does not require a real FieldGroup.
        """
        if mode_type == "angle":
            return AngleFieldMode()  # placeholder
        if mode_type == "object_height":
            return ObjectHeightFieldMode()  # placeholder
        raise ValueError(f"Unsupported canonical mode type: {mode_type}")

    @staticmethod
    def _last(arr: Any) -> float:
        """Return the last scalar from a possibly 2D array-like result.

        Trace APIs often return arrays with shape (num_surfaces, num_rays)
        or similar. This helper extracts the last value robustly.

        Args:
            arr: Array-like with at least one element.

        Returns:
            The last element coerced to float.

        Raises:
            ValueError: If array is empty or cannot be indexed.
        """
        try:
            return float(arr[-1])
        except Exception:  # noqa: BLE001
            # Try nested last access
            try:
                return float(arr[-1, -1])
            except Exception as exc:  # noqa: BLE001
                raise ValueError(
                    "Unexpected shape from paraxial trace output."
                ) from exc


class RealImageHeightSolver:
    def __init__(self):
        raise NotImplementedError("Real image height field mode not yet implemented.")
