[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vtk"
description = "VTK stub for running Optiland in WASM environments"
readme = { content-type = "text/markdown", text = "" }
license = { text = "" }
requires-python = ">=3.9,<3.14"
version = "9.4.2"