blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Start a Discussion
    url: https://github.com/HarrisonKramer/optiland/discussions
    about: Please use GitHub Discussions for questions, help, and general conversations.
