# tests/analysis/test_ray_fan.py
"""
Tests for the RayFan and BestFitRayFan analysis tools.
"""
import matplotlib
import matplotlib.pyplot as plt
import pytest
from unittest.mock import MagicMock

import optiland.backend as be
from optiland import analysis
from optiland.samples.objectives import CookeTriplet
from ..utils import assert_allclose

matplotlib.use("Agg")  # use non-interactive backend for testing


@pytest.fixture
def cooke_triplet():
    """Provides a CookeTriplet instance for testing."""
    return CookeTriplet()


class TestCookeTripletRayFan:
    """
    Tests the standard RayFan analysis for the Cooke Triplet lens system.
    """

    def test_ray_fan_data(self, set_test_backend, cooke_triplet):
        """
        Tests the underlying data generated by the RayFan analysis by
        comparing ray intercept coordinates against known values.
        """
        fan = analysis.RayFan(cooke_triplet)
        data = fan.data
        # On-axis, primary wavelength
        on_axis_primary_x = data["(0.0, 0.0)"]["0.55"]["x"]
        assert_allclose(on_axis_primary_x[0], 0.004195, atol=1e-5)
        # Off-axis, different wavelength
        off_axis_y = data["(0.0, 0.7)"]["0.65"]["y"]
        assert_allclose(off_axis_y[-1], 0.047721, atol=1e-5)

    def test_view_ray_fan(self, set_test_backend, cooke_triplet):
        """
        Tests the view method for generating a ray fan plot.
        """
        ray_fan = analysis.RayFan(cooke_triplet)
        fig, axes = ray_fan.view()
        assert fig is not None
        assert len(axes) > 0
        assert isinstance(fig, plt.Figure)
        assert all(isinstance(ax, plt.Axes) for ax in axes)
        plt.close(fig)

    def test_view_ray_fan_larger_fig(self, set_test_backend, cooke_triplet):
        """
        Tests that the view method can accept a custom figure size.
        """
        ray_fan = analysis.RayFan(cooke_triplet)
        fig, axes = ray_fan.view(figsize=(20, 10))
        assert fig is not None
        assert len(axes) > 0
        plt.close(fig)


class TestCookeTripletBestFitRayFan:
    """
    Tests the BestFitRayFan analysis, which plots ray aberrations with
    respect to the best-fit reference sphere.
    """

    def test_initialization(self, set_test_backend, cooke_triplet):
        """
        Tests that the BestFitRayFan class initializes correctly.
        """
        fan = analysis.BestFitRayFan(cooke_triplet)
        assert fan.num_rays_for_fit == 15
        assert fan.num_points == 257  # Default 256 becomes odd

    def test_best_fit_ray_fan_data(self, set_test_backend, cooke_triplet):
        """
        Compares the best-fit ray fan data to the standard ray fan data
        to ensure they are reasonably close.
        """
        fan_best_fit = analysis.BestFitRayFan(cooke_triplet, num_points=33, num_rays_for_fit=5)
        fan_standard = analysis.RayFan(cooke_triplet, num_points=33)
        field_key = f"{cooke_triplet.fields.get_field_coords()[1]}"
        wave_key = f"{cooke_triplet.primary_wavelength}"

        x_best_fit = fan_best_fit.data[field_key][wave_key]["x"]
        x_standard = fan_standard.data[field_key][wave_key]["x"]
        y_best_fit = fan_best_fit.data[field_key][wave_key]["y"]

        assert not be.all(be.isnan(x_best_fit))
        assert not be.all(be.isnan(y_best_fit))
        assert_allclose(x_best_fit, x_standard, atol=1e-4)
        assert_allclose(y_best_fit[0], -0.02689, atol=1e-5)

    def test_view_best_fit_ray_fan(self, set_test_backend, cooke_triplet):
        """
        Tests the view method for generating a best-fit ray fan plot.
        """
        ray_fan = analysis.BestFitRayFan(cooke_triplet)
        fig, axes = ray_fan.view()
        assert fig is not None
        assert len(axes) > 0
        plt.close(fig)

    def test_remove_distortion_with_invalid_central_ray(self, set_test_backend):
        """
        Tests that if the central ray is obscured, the distortion is removed
        by subtracting the mean of the valid rays.
        """
        mock_optic = MagicMock()
        mock_optic.primary_wavelength = 0.55
        fan = analysis.BestFitRayFan(mock_optic, num_points=5)
        fan.fields = [(0.0, 0.7)]
        fan.wavelengths = [0.55]

        # Simulate data where the central ray (index 2) has zero intensity
        intensity_with_obscuration = be.array([1.0, 1.0, 0.0, 1.0, 1.0])
        x_coords = be.array([10.0, 20.0, 999.0, 30.0, 40.0])
        y_coords = be.array([-4.0, -2.0, 888.0, 2.0, 4.0])
        fan.data = {
            "(0.0, 0.7)": {"0.55": {"x": x_coords, "y": y_coords, "intensity_x": intensity_with_obscuration, "intensity_y": intensity_with_obscuration}}
        }

        processed_data = fan._remove_distortion(fan.data)
        output_data = processed_data["(0.0, 0.7)"]["0.55"]

        # Expect offset to be mean of valid rays: mean([10,20,30,40])=25
        expected_x_final = x_coords - 25.0
        # Expect offset to be mean of valid rays: mean([-4,-2,2,4])=0
        expected_y_final = y_coords - 0.0

        assert_allclose(output_data["x"], expected_x_final)
        assert_allclose(output_data["y"], expected_y_final)