"""Core plotting functionalities for the Optiland library.

This module provides the main `Plotter` class, which is the primary interface
for creating various types of plots. It integrates with the `config` and
`themes` modules to allow for extensive customization of plot appearance.
"""
import numpy as np # Added for examples
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D # For 3D plotting
from . import config
from . import themes
from . import exceptions

class Plotter:
  """A class to create various plots using matplotlib with custom themes and configs.

  The `Plotter` class simplifies the process of generating common plots
  by integrating theme and configuration management directly into the
  plotting methods. It allows users to easily switch themes, update
  global plot settings, and create visualizations with consistent styling.

  Example:
      >>> from optiland.plotting import Plotter
      >>> plotter = Plotter()
      >>> x_values = list(range(5))
      >>> y_values = [x*x for x in x_values]
      >>> plotter.plot_line(x_values, y_values, title="My First Plot")
      # This will display the plot based on current theme and config.

      >>> plotter.set_theme("dark")
      >>> plotter.update_config("font.size_title", 20)
      >>> plotter.plot_scatter(x_values, y_values, title="Dark Scatter, Large Title")
      # Plot is shown with dark theme and a larger title font.
  """

  def __init__(self):
    """Initializes the Plotter.

    The plotter relies on the global settings defined in the
    `optiland.plotting.config` and `optiland.plotting.themes` modules.
    """
    # No specific state needed in __init__ for now, as it uses global
    # config/theme modules.
    pass

  def set_theme(self, theme_name: str):
    """Sets the active theme for all subsequent plots generated by this plotter.

    Args:
      theme_name: The name of the theme to activate (e.g., 'light', 'dark').

    Raises:
      ValueError: If the theme_name is not a defined theme.
    """
    themes.set_active_theme(theme_name)

  def update_config(self, key: str, value):
    """Updates a global plotting configuration setting.

    This change will affect all subsequent plots.

    Args:
      key: The dot-separated configuration key (e.g., 'figure.figsize').
      value: The new value for the configuration setting.

    Raises:
      KeyError: If the key is not a valid configuration option.
      TypeError: If the value type is incorrect for the given key.
    """
    config.set_config(key, value)

  def get_current_theme_settings(self) -> dict:
    """Retrieves the dictionary of settings for the currently active theme.

    Returns:
      A dictionary containing all key-value pairs for the active theme.
    """
    return themes.get_active_theme_dict()

  def get_config_value(self, key: str):
    """Retrieves a specific configuration value.

    Args:
      key: The dot-separated configuration key.

    Returns:
      The value of the configuration setting.

    Raises:
      KeyError: If the key is not found.
    """
    return config.get_config(key)

  def _apply_theme_and_config_to_ax(self, ax, theme_settings: dict, plot_configs: dict):
    """Applies theme and configuration settings to a matplotlib Axes object.

    This is a helper method to centralize common styling operations.

    Args:
      ax: The matplotlib.axes.Axes object to style.
      theme_settings: A dictionary of theme settings.
      plot_configs: A dictionary of relevant plot configurations.
    """
    ax.set_facecolor(theme_settings.get('axes.facecolor', '#FFFFFF'))
    ax.grid(
        True, # TODO: Make grid state configurable
        color=theme_settings.get('grid.color', '#D0D0D0'),
        alpha=theme_settings.get('grid.alpha', 0.8)
    )
    ax.spines['top'].set_edgecolor(theme_settings.get('axes.edgecolor', '#333333'))
    ax.spines['bottom'].set_edgecolor(theme_settings.get('axes.edgecolor', '#333333'))
    ax.spines['left'].set_edgecolor(theme_settings.get('axes.edgecolor', '#333333'))
    ax.spines['right'].set_edgecolor(theme_settings.get('axes.edgecolor', '#333333'))

    # Apply font sizes from config
    ax.title.set_fontsize(plot_configs.get('font.size_title', 16))
    ax.xaxis.label.set_fontsize(plot_configs.get('font.size_label', 14))
    ax.yaxis.label.set_fontsize(plot_configs.get('font.size_label', 14))
    ax.tick_params(labelsize=plot_configs.get('font.size_legend', 12)) # Using legend size for 2D tick labels

    if hasattr(ax, 'zaxis'): # 3D specific settings
        ax.zaxis.label.set_fontsize(plot_configs.get('font.size_label', 14))
        # Apply pane colors for 3D plots
        pane_color = theme_settings.get('axes3d.pane_color', theme_settings.get('axes.facecolor', '#EAEAF2'))
        ax.xaxis.set_pane_color(pane_color)
        ax.yaxis.set_pane_color(pane_color)
        ax.zaxis.set_pane_color(pane_color)

        # Apply 3D grid color
        grid3d_color = theme_settings.get('axes3d.grid_color', theme_settings.get('grid.color', '#D0D0D0'))
        ax.w_xaxis._axinfo.update({'grid': {'color': grid3d_color, 'linewidth': 0.5, 'linestyle': ':'}})
        ax.w_yaxis._axinfo.update({'grid': {'color': grid3d_color, 'linewidth': 0.5, 'linestyle': ':'}})
        ax.w_zaxis._axinfo.update({'grid': {'color': grid3d_color, 'linewidth': 0.5, 'linestyle': ':'}})

        # Set face color for the 3D axes background itself
        ax.set_facecolor(theme_settings.get('axes3d.facecolor', theme_settings.get('axes.facecolor', '#FFFFFF')))

        # Tick label colors for 3D (already handled by tick_params if general, but can be specific)
        ax.tick_params(axis='x', colors=theme_settings.get('xtick.color', '#333333'))
        ax.tick_params(axis='y', colors=theme_settings.get('ytick.color', '#333333'))
        ax.tick_params(axis='z', colors=theme_settings.get('xtick.color', '#333333')) # Assuming ztick uses similar color
    else: # 2D specific settings that might not apply or need adjustment for 3D
        ax.grid(
            True, # TODO: Make grid state configurable
            color=theme_settings.get('grid.color', '#D0D0D0'),
            alpha=theme_settings.get('grid.alpha', 0.8)
        )
        ax.spines['top'].set_edgecolor(theme_settings.get('axes.edgecolor', '#333333'))
        ax.spines['bottom'].set_edgecolor(theme_settings.get('axes.edgecolor', '#333333'))
        ax.spines['left'].set_edgecolor(theme_settings.get('axes.edgecolor', '#333333'))
        ax.spines['right'].set_edgecolor(theme_settings.get('axes.edgecolor', '#333333'))


  def plot_line(
      self,
      x,
      y,
      title: str = None,
      xlabel: str = None,
      ylabel: str = None,
      legend_label: str = None,
      return_fig_ax: bool = None,
      **kwargs
  ):
    """Plots a line graph.

    Generates a line plot with the given data, applying current theme and
    configuration settings.

    Args:
      x: Array-like data for the x-axis.
      y: Array-like data for the y-axis.
      title: Optional title for the plot.
      xlabel: Optional label for the x-axis.
      ylabel: Optional label for the y-axis.
      legend_label: Optional label for the line, used if a legend is shown.
      return_fig_ax: Optional. If True, returns (fig, ax). If False, displays
          the plot and returns None. If None, uses the global
          'plot.return_fig_ax' and 'plot.show_on_draw' config.
      **kwargs: Additional keyword arguments passed to `matplotlib.pyplot.plot()`.

    Returns:
      Optionally, a tuple (matplotlib.figure.Figure, matplotlib.axes.Axes)
      if `return_fig_ax` is True or if the global config 'plot.return_fig_ax'
      is True and `return_fig_ax` is None. Otherwise, returns None.

    Raises:
      exceptions.InvalidPlotDataError: If input data is unsuitable.
      exceptions.ConfigurationError: If a configuration key is missing.
      exceptions.ThemeNotFoundError: If a theme key is missing.

    Example:
        >>> from optiland.plotting import Plotter
        >>> plotter = Plotter()
        >>> x = [i/10.0 for i in range(50)]
        >>> y = [val**2 for val in x]
        >>> plotter.plot_line(x, y, title="Squared Values",
        ...                   xlabel="X-value", ylabel="Y-value",
        ...                   legend_label="y = x^2")
        # The plot is displayed automatically if 'plot.show_on_draw' is True.

        To get fig and ax objects for further customization:
        >>> fig, ax = plotter.plot_line(x, y, title="Customized Plot", return_fig_ax=True)
        >>> if fig and ax: # Check if objects were returned
        ...     ax.text(0.5, 0.5, "Custom Annotation", transform=ax.transAxes,
        ...             ha='center', color='blue', fontsize=12)
        ...     # If 'plot.show_on_draw' is False (globally or due to return_fig_ax=True),
        ...     # and you need to show it:
        ...     # import matplotlib.pyplot as plt
        ...     # plt.show()

    Example:
        >>> from optiland.plotting import Plotter
        >>> plotter = Plotter()
        >>> x_coords = [1, 2.5, 3, 4.2, 5]
        >>> y_coords = [2, 3, 2.5, 4, 3.5]

        First, a simple scatter plot with default settings:
        >>> plotter.plot_scatter(x_coords, y_coords, title="Default Scatter Plot")

        Now, customize theme and configuration:
        >>> plotter.set_theme('dark')
        >>> plotter.update_config('lines.markersize', 10) # Affects scatter marker size
        >>> plotter.update_config('figure.figsize', (8, 8)) # Make figure larger
        >>> fig, ax = plotter.plot_scatter(x_coords, y_coords,
        ...                                title="Dark Scatter with Large Markers",
        ...                                xlabel="X Coordinate", ylabel="Y Coordinate",
        ...                                legend_label="Data Points",
        ...                                return_fig_ax=True)
        >>> if fig and ax:
        ...    # Add custom grid lines
        ...    ax.grid(True, linestyle=':', linewidth='0.5', color='gray')
        ...    # import matplotlib.pyplot as plt
        ...    # plt.show() # If needed
    """
    try:
        # Basic data validation
        if not (hasattr(x, '__len__') and hasattr(y, '__len__') and len(x) == len(y)):
            raise exceptions.InvalidPlotDataError("x and y must be array-like and have the same length.")
        if len(x) == 0:
            raise exceptions.InvalidPlotDataError("Input data x and y cannot be empty.")

        theme_settings = self.get_current_theme_settings()

        # Determine if objects should be returned or plot shown
        if return_fig_ax is None:
            should_return_objects = self.get_config_value('plot.return_fig_ax')
            show_plot_on_draw = self.get_config_value('plot.show_on_draw')
    else:
      should_return_objects = return_fig_ax
      show_plot_on_draw = not return_fig_ax # If explicitly asking for return, don't show.

    fig, ax = plt.subplots(figsize=self.get_config_value('figure.figsize'))
    fig.set_facecolor(theme_settings.get('figure.facecolor', '#FFFFFF'))

    plot_configs = {
        'font.size_title': self.get_config_value('font.size_title'),
        'font.size_label': self.get_config_value('font.size_label'),
        'font.size_legend': self.get_config_value('font.size_legend'),
    }
    self._apply_theme_and_config_to_ax(ax, theme_settings, plot_configs)

    # Plot data
    line_color = kwargs.pop('color', theme_settings.get('lines.color', '#007ACC'))
    linewidth = kwargs.pop('linewidth', self.get_config_value('lines.linewidth'))
    markersize = kwargs.pop('markersize', self.get_config_value('lines.markersize'))

    ax.plot(
        x, y, label=legend_label, color=line_color,
        linewidth=linewidth, markersize=markersize, **kwargs
    )

    # Set title and labels
    if title:
      ax.set_title(
          title,
          color=theme_settings.get('axes.titlecolor', '#333333'),
          fontsize=self.get_config_value('font.size_title')
      )
    if xlabel:
      ax.set_xlabel(
          xlabel,
          color=theme_settings.get('axes.labelcolor', '#333333'),
          fontsize=self.get_config_value('font.size_label')
      )
    if ylabel:
      ax.set_ylabel(
          ylabel,
          color=theme_settings.get('axes.labelcolor', '#333333'),
          fontsize=self.get_config_value('font.size_label')
      )

    # Set tick colors
    ax.tick_params(axis='x', colors=theme_settings.get('xtick.color', '#333333'))
    ax.tick_params(axis='y', colors=theme_settings.get('ytick.color', '#333333'))

    # Add legend
    if legend_label:
      legend = ax.legend(fontsize=self.get_config_value('font.size_legend'))
      # Set legend text color (requires iterating through texts)
      legend_text_color = theme_settings.get('legend.labelcolor', theme_settings.get('text.color', '#333333'))
      for text in legend.get_texts():
          text.set_color(legend_text_color)
      if theme_settings.get('legend.facecolor'):
        legend.get_frame().set_facecolor(theme_settings.get('legend.facecolor'))
      if theme_settings.get('legend.edgecolor'):
        legend.get_frame().set_edgecolor(theme_settings.get('legend.edgecolor'))


    if show_plot_on_draw and not should_return_objects:
      plt.show()

    if should_return_objects:
      return fig, ax
    else:
      plt.close(fig)
      return None
    except exceptions.PlottingError: # Re-raise our own plotting errors
        raise
    except Exception as e: # Wrap other unexpected errors
        raise exceptions.PlottingError(f"An unexpected error occurred in plot_line: {e}") from e

  def plot_image(
      self,
      image_data,
      title: str = None,
      xlabel: str = None,
      ylabel: str = None,
      cmap: str = None,
      show_colorbar: bool = True,
      return_fig_ax: bool = None,
      **kwargs
  ):
    """Plots 2D image data, such as a heatmap.

    Generates an image plot using `imshow`, applying current theme and
    configuration settings.

    Args:
      image_data: A 2D array-like structure (e.g., NumPy array) containing
          the image data.
      title: Optional title for the plot.
      xlabel: Optional label for the x-axis.
      ylabel: Optional label for the y-axis.
      cmap: Optional colormap name (string). If None, uses the
          'image.cmap' value from the global configuration.
      show_colorbar: If True, a colorbar is added to the plot.
      return_fig_ax: Optional. If True, returns (fig, ax). If False, displays
          the plot and returns None. If None, uses the global
          'plot.return_fig_ax' and 'plot.show_on_draw' config.
      **kwargs: Additional keyword arguments passed to `matplotlib.pyplot.imshow()`.

    Returns:
      Optionally, a tuple (matplotlib.figure.Figure, matplotlib.axes.Axes)
      if `return_fig_ax` is True or if the global config 'plot.return_fig_ax'
      is True and `return_fig_ax` is None. Otherwise, returns None.

    Raises:
      exceptions.InvalidPlotDataError: If input data is unsuitable.
      exceptions.ConfigurationError: If a configuration key is missing.
      exceptions.ThemeNotFoundError: If a theme key is missing.

    Example:
        >>> import numpy as np
        >>> from optiland.plotting import Plotter
        >>> plotter = Plotter()
        >>> data = np.random.rand(10, 10)
        >>> plotter.plot_image(data, title="Heatmap Example",
        ...                    xlabel="X-axis", ylabel="Y-axis",
        ...                    cmap='viridis')
        # Plot is displayed with viridis colormap.

        >>> plotter.set_theme('dark')
        >>> fig, ax = plotter.plot_image(data, title="Dark Heatmap with different cmap",
        ...                              cmap='inferno', return_fig_ax=True)
        >>> if fig and ax:
        ...     ax.set_xticklabels([]) # Example: remove x-tick labels
        ...     # import matplotlib.pyplot as plt
        ...     # plt.show() # If needed
    """
    try:
        # Basic data validation for image_data
        img_array = np.asarray(image_data)
        if img_array.ndim != 2:
            raise exceptions.InvalidPlotDataError(
                f"image_data must be a 2D array-like structure. Got {img_array.ndim} dimensions."
            )
        if img_array.size == 0:
            raise exceptions.InvalidPlotDataError("image_data cannot be empty.")

        theme_settings = self.get_current_theme_settings()

        if return_fig_ax is None:
            should_return_objects = self.get_config_value('plot.return_fig_ax')
            show_plot_on_draw = self.get_config_value('plot.show_on_draw')
    else:
      should_return_objects = return_fig_ax
      show_plot_on_draw = not return_fig_ax

    fig, ax = plt.subplots(figsize=self.get_config_value('figure.figsize'))
    fig.set_facecolor(theme_settings.get('figure.facecolor', '#FFFFFF'))

    plot_configs = {
        'font.size_title': self.get_config_value('font.size_title'),
        'font.size_label': self.get_config_value('font.size_label'),
        'font.size_legend': self.get_config_value('font.size_legend'), # Used for tick labels by _apply_theme
    }
    self._apply_theme_and_config_to_ax(ax, theme_settings, plot_configs)

    current_cmap = cmap or self.get_config_value('image.cmap')

    im = ax.imshow(image_data, cmap=current_cmap, **kwargs)

    if title:
      ax.set_title(
          title,
          color=theme_settings.get('axes.titlecolor', '#333333'),
          fontsize=self.get_config_value('font.size_title')
      )
    if xlabel:
      ax.set_xlabel(
          xlabel,
          color=theme_settings.get('axes.labelcolor', '#333333'),
          fontsize=self.get_config_value('font.size_label')
      )
    if ylabel:
      ax.set_ylabel(
          ylabel,
          color=theme_settings.get('axes.labelcolor', '#333333'),
          fontsize=self.get_config_value('font.size_label')
      )

    ax.tick_params(axis='x', colors=theme_settings.get('xtick.color', '#333333'))
    ax.tick_params(axis='y', colors=theme_settings.get('ytick.color', '#333333'))

    if show_colorbar:
      cb = fig.colorbar(im, ax=ax)
      # Basic theming for colorbar ticks
      cb.ax.tick_params(colors=theme_settings.get('ytick.color', '#333333'),
                        labelsize=self.get_config_value('font.size_legend')-2) # smaller font for colorbar

    if show_plot_on_draw and not should_return_objects:
      plt.show()

    if should_return_objects:
      return fig, ax
    else:
      plt.close(fig)
      return None
    except exceptions.PlottingError:
        raise
    except Exception as e:
        raise exceptions.PlottingError(f"An unexpected error occurred in plot_image: {e}") from e

  def plot_subplots(
      self,
      num_rows: int,
      num_cols: int,
      plot_callbacks: list,
      sharex: bool = False,
      sharey: bool = False,
      main_title: str = None,
      return_fig_axs: bool = None,
      **fig_kwargs
  ):
    """Creates a figure with multiple subplots arranged in a grid.

    Each subplot is populated by a user-provided callback function.

    Args:
      num_rows: Number of rows in the subplot grid.
      num_cols: Number of columns in the subplot grid.
      plot_callbacks: A list of functions. Each function must accept two
          arguments: a `matplotlib.axes.Axes` object (the subplot's axes)
          and an integer `index` (the 0-based index of the subplot in
          the flattened grid). The callback is responsible for plotting data
          on the provided `ax`.
      sharex: Whether subplots should share the x-axis. See `plt.subplots`.
      sharey: Whether subplots should share the y-axis. See `plt.subplots`.
      main_title: Optional super-title for the entire figure.
      return_fig_axs: Optional. If True, returns (fig, axs). If False, displays
          the plot and returns None. If None, uses the global
          'plot.return_fig_ax' (note: singular 'ax' in config name)
          and 'plot.show_on_draw' config.
      **fig_kwargs: Additional keyword arguments passed to `matplotlib.pyplot.subplots()`.

    Returns:
      Optionally, a tuple (matplotlib.figure.Figure, array of matplotlib.axes.Axes)
      if `return_fig_axs` is True or if the global config 'plot.return_fig_ax'
      is True and `return_fig_axs` is None. Otherwise, returns None.

    Raises:
      ValueError: If the number of callbacks does not match `num_rows * num_cols`
                  (this is a specific argument validation, kept as ValueError).
      exceptions.ConfigurationError: If a configuration key is missing.
      exceptions.ThemeNotFoundError: If a theme key is missing.
      exceptions.InvalidPlotDataError: If plot_callbacks is not a list or is empty.


    Example:
        >>> import numpy as np
        >>> from optiland.plotting import Plotter
        >>> plotter = Plotter()
        >>>
        >>> def plot_sine(ax, index):
        ...     x = np.linspace(0, 2 * np.pi, 100)
        ...     y = np.sin(x + index * np.pi / 2)
        ...     ax.plot(x, y) # Line color will be from theme by default
        ...     ax.set_title(f'Plot {index+1}: Sin(x + {index}\\u03C0/2)') # Title color from theme
        ...     # ax.set_xlabel("X") # Labels can be set here too
        ...     # ax.set_ylabel("Y")
        >>>
        >>> def plot_random_scatter(ax, index):
        ...     x_scatter = np.random.rand(20)
        ...     y_scatter = np.random.rand(20)
        ...     # Example of overriding theme color for this specific subplot
        ...     ax.scatter(x_scatter, y_scatter, color='purple', s=50)
        ...     ax.set_title(f'Plot {index+1}: Random Scatter')
        >>>
        >>> callbacks = [plot_sine, plot_random_scatter, plot_sine, plot_random_scatter]
        >>> plotter.plot_subplots(2, 2, callbacks, main_title="Multiple Plots Demo")
        # Plot is displayed.
        >>>
        >>> # Example with returning figure and axes array
        >>> fig, axs = plotter.plot_subplots(1, 2, [plot_sine, plot_random_scatter],
        ...                                  main_title="Two Subplots", return_fig_axs=True)
        >>> if fig and axs.size == 2: # Check if objects were returned (axs is a numpy array)
        ...    axs[0].set_xlabel("X-axis for Sine")
        ...    axs[1].set_ylabel("Y-axis for Scatter")
        ...    fig.tight_layout(rect=[0, 0, 1, 0.96]) # Adjust layout for main_title
        ...    # import matplotlib.pyplot as plt
        ...    # plt.show() # If needed
    """
    try:
        if not isinstance(plot_callbacks, list) or not plot_callbacks:
            raise exceptions.InvalidPlotDataError("plot_callbacks must be a non-empty list of functions.")
        if len(plot_callbacks) != num_rows * num_cols:
            raise ValueError( # Keeping ValueError for direct argument validation
                f"Number of plot_callbacks ({len(plot_callbacks)}) must match "
                f"num_rows * num_cols ({num_rows * num_cols})."
            )
        if not all(callable(cb) for cb in plot_callbacks):
            raise exceptions.InvalidPlotDataError("All items in plot_callbacks must be callable functions.")


        theme_settings = self.get_current_theme_settings()

        # For return_fig_axs, we use the singular 'plot.return_fig_ax' from config
        if return_fig_axs is None:
            should_return_objects = self.get_config_value('plot.return_fig_ax')
            show_plot_on_draw = self.get_config_value('plot.show_on_draw')
    else:
      should_return_objects = return_fig_axs
      show_plot_on_draw = not return_fig_axs

    fig, axs = plt.subplots(
        num_rows, num_cols, sharex=sharex, sharey=sharey,
        figsize=self.get_config_value('figure.figsize'), **fig_kwargs
    )
    fig.set_facecolor(theme_settings.get('figure.facecolor', '#FFFFFF'))

    plot_configs = {
        'font.size_title': self.get_config_value('font.size_title'),
        'font.size_label': self.get_config_value('font.size_label'),
        'font.size_legend': self.get_config_value('font.size_legend'),
    }

    if main_title:
      fig.suptitle(
          main_title,
          fontsize=plot_configs['font.size_title'] + 2, # Slightly larger for main title
          color=theme_settings.get('axes.titlecolor', '#333333'),
          # y=0.98 # Adjust position if needed
      )

    # Ensure axs is always an array, even for single subplot case (e.g. 1,1)
    if not isinstance(axs, np.ndarray):
        axs_flat = [axs]
    else:
        axs_flat = axs.flat

    for i, ax_subplot in enumerate(axs_flat):
      if i < len(plot_callbacks):
        self._apply_theme_and_config_to_ax(ax_subplot, theme_settings, plot_configs)
        # Titles and labels within callbacks will also use theme colors
        # if they use ax.set_title, ax.set_xlabel etc. directly.
        plot_callbacks[i](ax_subplot, i)

    # Improve layout, especially if there's a suptitle
    if main_title:
        fig.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust rect to make space for suptitle
    else:
        fig.tight_layout()


    if show_plot_on_draw and not should_return_objects:
      plt.show()

    if should_return_objects:
      return fig, axs # Return the potentially multi-dimensional array `axs`
    else:
      plt.close(fig)
      return None
    except exceptions.PlottingError:
        raise
    except ValueError: # Re-raise argument validation error
        raise
    except Exception as e:
        raise exceptions.PlottingError(f"An unexpected error occurred in plot_subplots: {e}") from e

  def plot_line_3d(
      self,
      x, y, z,
      title: str = None,
      xlabel: str = None,
      ylabel: str = None,
      zlabel: str = None,
      legend_label: str = None,
      return_fig_ax: bool = None,
      **kwargs
  ):
    """Plots a 3D line graph.

    Generates a 3D line plot with the given data, applying current theme and
    configuration settings.

    Args:
      x: Array-like data for the x-axis.
      y: Array-like data for the y-axis.
      z: Array-like data for the z-axis.
      title: Optional title for the plot.
      xlabel: Optional label for the x-axis.
      ylabel: Optional label for the y-axis.
      zlabel: Optional label for the z-axis.
      legend_label: Optional label for the line, used if a legend is shown.
      return_fig_ax: Optional. If True, returns (fig, ax). If False, displays
          the plot. If None, uses global 'plot.return_fig_ax' and
          'plot.show_on_draw' config.
      **kwargs: Additional keyword arguments passed to `ax.plot()`.

    Returns:
      Optionally, a tuple (matplotlib.figure.Figure, matplotlib.axes.Axes3D)
      if `return_fig_ax` is True or if global config 'plot.return_fig_ax'
      is True and `return_fig_ax` is None. Otherwise, returns None.

    Raises:
      exceptions.InvalidPlotDataError: If input data is unsuitable.
      exceptions.ConfigurationError: If a configuration key is missing.
      exceptions.ThemeNotFoundError: If a theme key is missing.

    Example:
        >>> import numpy as np
        >>> from optiland.plotting import Plotter
        >>> plotter = Plotter()
        >>> t = np.linspace(-4 * np.pi, 4 * np.pi, 100)
        >>> x = np.sin(t)
        >>> y = np.cos(t)
        >>> z = t / (4 * np.pi)
        >>> plotter.plot_line_3d(x, y, z, title="3D Helix", legend_label="Path")
        >>> plotter.set_theme('dark')
        >>> fig, ax = plotter.plot_line_3d(x, y, z, title="Dark Helix", return_fig_ax=True)
        >>> if fig and ax:
        ...     ax.view_init(elev=30, azim=60) # Change view angle
        ...     # import matplotlib.pyplot as plt
        ...     # plt.show() # If needed
    """
    try:
        if not (hasattr(x, '__len__') and hasattr(y, '__len__') and hasattr(z, '__len__') and
                len(x) == len(y) == len(z)):
            raise exceptions.InvalidPlotDataError(
                "x, y, and z must be array-like and have the same length."
            )
        if len(x) == 0:
            raise exceptions.InvalidPlotDataError("Input data x, y, z cannot be empty.")

        theme_settings = self.get_current_theme_settings()

        if return_fig_ax is None:
            should_return_objects = self.get_config_value('plot.return_fig_ax')
            show_plot_on_draw = self.get_config_value('plot.show_on_draw')
    else:
      should_return_objects = return_fig_ax
      show_plot_on_draw = not return_fig_ax

    fig = plt.figure(figsize=self.get_config_value('figure.figsize'))
    fig.set_facecolor(theme_settings.get('figure.facecolor', '#FFFFFF'))
    ax = fig.add_subplot(111, projection='3d')

    plot_configs = {
        'font.size_title': self.get_config_value('font.size_title'),
        'font.size_label': self.get_config_value('font.size_label'),
        'font.size_legend': self.get_config_value('font.size_legend'),
    }
    # This will now also handle 3D specific theming like pane colors
    self._apply_theme_and_config_to_ax(ax, theme_settings, plot_configs)

    line_color = kwargs.pop('color', theme_settings.get('lines.color', '#007ACC'))
    linewidth = kwargs.pop('linewidth', self.get_config_value('lines.linewidth'))

    ax.plot(x, y, z, label=legend_label, color=line_color, linewidth=linewidth, **kwargs)

    if title:
      ax.set_title(title, color=theme_settings.get('axes.titlecolor', '#333333'),
                   fontsize=plot_configs['font.size_title'])
    if xlabel:
      ax.set_xlabel(xlabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])
    if ylabel:
      ax.set_ylabel(ylabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])
    if zlabel:
      ax.set_zlabel(zlabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])

    # Tick colors are handled by _apply_theme_and_config_to_ax for 3D

    if legend_label:
      legend = ax.legend(fontsize=plot_configs['font.size_legend'])
      legend_text_color = theme_settings.get('legend.labelcolor', theme_settings.get('text.color', '#333333'))
      for text_obj in legend.get_texts(): # Matplotlib uses 'text' not 'labelcolor' for legend
          text_obj.set_color(legend_text_color)
      if theme_settings.get('legend.facecolor'):
        legend.get_frame().set_facecolor(theme_settings.get('legend.facecolor'))
      if theme_settings.get('legend.edgecolor'):
        legend.get_frame().set_edgecolor(theme_settings.get('legend.edgecolor'))

    if show_plot_on_draw and not should_return_objects:
      plt.show()

    if should_return_objects:
      return fig, ax
    else:
      plt.close(fig)
      return None
    except exceptions.PlottingError:
        raise
    except Exception as e:
        raise exceptions.PlottingError(f"An unexpected error occurred in plot_line_3d: {e}") from e

  def plot_scatter_3d(
      self,
      x, y, z,
      title: str = None,
      xlabel: str = None,
      ylabel: str = None,
      zlabel: str = None,
      legend_label: str = None, # Note: legend for scatter3d can be tricky if colors/sizes vary per point
      return_fig_ax: bool = None,
      **kwargs
  ):
    """Plots a 3D scatter graph.

    Generates a 3D scatter plot, applying current theme and configuration.

    Args:
      x: Array-like data for the x-axis.
      y: Array-like data for the y-axis.
      z: Array-like data for the z-axis.
      title: Optional title for the plot.
      xlabel: Optional label for the x-axis.
      ylabel: Optional label for the y-axis.
      zlabel: Optional label for the z-axis.
      legend_label: Optional label for the points, used if a legend is shown.
      return_fig_ax: Optional. If True, returns (fig, ax). If False, displays.
          If None, uses global config.
      **kwargs: Additional keyword arguments passed to `ax.scatter()`.
          Useful for `c` (color array), `s` (size array), `marker`.

    Returns:
      Optionally, a tuple (matplotlib.figure.Figure, matplotlib.axes.Axes3D)
      if `return_fig_ax` is True or if global config 'plot.return_fig_ax'
      is True and `return_fig_ax` is None. Otherwise, returns None.

    Raises:
      exceptions.InvalidPlotDataError: If input data is unsuitable.
      exceptions.ConfigurationError: If a configuration key is missing.
      exceptions.ThemeNotFoundError: If a theme key is missing.

    Example:
        >>> import numpy as np
        >>> from optiland.plotting import Plotter
        >>> plotter = Plotter()
        >>> x_rand = np.random.rand(50)
        >>> y_rand = np.random.rand(50)
        >>> z_rand = np.random.rand(50)
        >>> colors = np.random.rand(50) # Per-point color
        >>> sizes = 100 * np.random.rand(50) # Per-point size
        >>> plotter.plot_scatter_3d(x_rand, y_rand, z_rand, title="3D Scatter Points",
        ...                         c=colors, s=sizes, cmap='viridis', legend_label="Random Data")
        # Note: legend_label might not be effective if 'c' is an array for colors.
        # A colorbar might be more appropriate if 'c' maps to a cmap.
    """
    try:
        if not (hasattr(x, '__len__') and hasattr(y, '__len__') and hasattr(z, '__len__') and
                len(x) == len(y) == len(z)):
            raise exceptions.InvalidPlotDataError(
                "x, y, and z must be array-like and have the same length."
            )
        if len(x) == 0:
            raise exceptions.InvalidPlotDataError("Input data x, y, z cannot be empty.")

        theme_settings = self.get_current_theme_settings()

        if return_fig_ax is None:
            should_return_objects = self.get_config_value('plot.return_fig_ax')
            show_plot_on_draw = self.get_config_value('plot.show_on_draw')
    else:
      should_return_objects = return_fig_ax
      show_plot_on_draw = not return_fig_ax

    fig = plt.figure(figsize=self.get_config_value('figure.figsize'))
    fig.set_facecolor(theme_settings.get('figure.facecolor', '#FFFFFF'))
    ax = fig.add_subplot(111, projection='3d')

    plot_configs = {
        'font.size_title': self.get_config_value('font.size_title'),
        'font.size_label': self.get_config_value('font.size_label'),
        'font.size_legend': self.get_config_value('font.size_legend'),
    }
    self._apply_theme_and_config_to_ax(ax, theme_settings, plot_configs)

    # Default marker color from theme, allow override by 'c' or 'color' in kwargs
    marker_color = kwargs.pop('c', kwargs.pop('color', theme_settings.get('lines.color', '#007ACC')))
    # Default marker size from config (squared for scatter 's'), allow override by 's'
    marker_size = kwargs.pop('s', self.get_config_value('lines.markersize')**2)

    ax.scatter(x, y, z, label=legend_label, color=marker_color, s=marker_size, **kwargs)

    if title:
      ax.set_title(title, color=theme_settings.get('axes.titlecolor', '#333333'),
                   fontsize=plot_configs['font.size_title'])
    if xlabel:
      ax.set_xlabel(xlabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])
    if ylabel:
      ax.set_ylabel(ylabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])
    if zlabel:
      ax.set_zlabel(zlabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])

    if legend_label: # Legend for 3D scatter can be simple if color/size is uniform
      legend = ax.legend(fontsize=plot_configs['font.size_legend'])
      legend_text_color = theme_settings.get('legend.labelcolor', theme_settings.get('text.color', '#333333'))
      for text_obj in legend.get_texts():
          text_obj.set_color(legend_text_color)
      if theme_settings.get('legend.facecolor'):
        legend.get_frame().set_facecolor(theme_settings.get('legend.facecolor'))
      if theme_settings.get('legend.edgecolor'):
        legend.get_frame().set_edgecolor(theme_settings.get('legend.edgecolor'))

    if show_plot_on_draw and not should_return_objects:
      plt.show()

    if should_return_objects:
      return fig, ax
    else:
      plt.close(fig)
      return None
    except exceptions.PlottingError:
        raise
    except Exception as e:
        raise exceptions.PlottingError(f"An unexpected error occurred in plot_scatter_3d: {e}") from e

  def plot_surface(
      self, X, Y, Z,
      title: str = None,
      xlabel: str = None,
      ylabel: str = None,
      zlabel: str = None,
      cmap: str = None,
      show_colorbar: bool = True,
      return_fig_ax: bool = None,
      **kwargs
  ):
    """Plots a 3D surface.

    Generates a 3D surface plot, applying theme and configuration.

    Args:
      X: 2D array of x-coordinates (e.g., from np.meshgrid).
      Y: 2D array of y-coordinates (e.g., from np.meshgrid).
      Z: 2D array of z-values corresponding to (X, Y).
      title: Optional title for the plot.
      xlabel: Optional label for the x-axis.
      ylabel: Optional label for the y-axis.
      zlabel: Optional label for the z-axis.
      cmap: Optional colormap name. Defaults to 'image.cmap' from config.
      show_colorbar: If True, adds a colorbar.
      return_fig_ax: Optional. If True, returns (fig, ax). If False, displays.
          If None, uses global config.
      **kwargs: Additional keyword arguments passed to `ax.plot_surface()`.
          Common arguments: `rstride`, `cstride`, `linewidth`, `edgecolor`.

    Returns:
      Optionally, a tuple (matplotlib.figure.Figure, matplotlib.axes.Axes3D)
      if `return_fig_ax` is True or if global config 'plot.return_fig_ax'
      is True and `return_fig_ax` is None. Otherwise, returns None.

    Raises:
      exceptions.InvalidPlotDataError: If input data X, Y, Z are unsuitable (e.g., not 2D or mismatched shapes).
      exceptions.ConfigurationError: If a configuration key is missing.
      exceptions.ThemeNotFoundError: If a theme key is missing.

    Example:
        >>> import numpy as np
        >>> from optiland.plotting import Plotter
        >>> plotter = Plotter()
        >>> x_surf = np.arange(-5, 5, 0.25)
        >>> y_surf = np.arange(-5, 5, 0.25)
        >>> X_surf, Y_surf = np.meshgrid(x_surf, y_surf)
        >>> R = np.sqrt(X_surf**2 + Y_surf**2)
        >>> Z_surf = np.sin(R)
        >>> plotter.plot_surface(X_surf, Y_surf, Z_surf, title="3D Surface (Sine Wave)",
        ...                      cmap='coolwarm', edgecolor='k', linewidth=0.2)
    """
    try:
        X_arr, Y_arr, Z_arr = np.asarray(X), np.asarray(Y), np.asarray(Z)
        if not (X_arr.ndim == 2 and Y_arr.ndim == 2 and Z_arr.ndim == 2):
            raise exceptions.InvalidPlotDataError("X, Y, and Z must be 2D array-like structures.")
        if not (X_arr.shape == Y_arr.shape == Z_arr.shape):
            raise exceptions.InvalidPlotDataError("X, Y, and Z must have the same shape.")
        if X_arr.size == 0:
            raise exceptions.InvalidPlotDataError("Input data X, Y, Z cannot be empty.")

        theme_settings = self.get_current_theme_settings()

        if return_fig_ax is None:
            should_return_objects = self.get_config_value('plot.return_fig_ax')
            show_plot_on_draw = self.get_config_value('plot.show_on_draw')
    else:
      should_return_objects = return_fig_ax
      show_plot_on_draw = not return_fig_ax

    fig = plt.figure(figsize=self.get_config_value('figure.figsize'))
    fig.set_facecolor(theme_settings.get('figure.facecolor', '#FFFFFF'))
    ax = fig.add_subplot(111, projection='3d')

    plot_configs = {
        'font.size_title': self.get_config_value('font.size_title'),
        'font.size_label': self.get_config_value('font.size_label'),
        'font.size_legend': self.get_config_value('font.size_legend'),
    }
    self._apply_theme_and_config_to_ax(ax, theme_settings, plot_configs)

    current_cmap = cmap or self.get_config_value('image.cmap')
    # Default edgecolor from theme if not provided in kwargs
    kwargs.setdefault('edgecolor', theme_settings.get('axes.edgecolor', 'none'))
    kwargs.setdefault('linewidth', 0.5)


    surf = ax.plot_surface(X, Y, Z, cmap=current_cmap, **kwargs)

    if title:
      ax.set_title(title, color=theme_settings.get('axes.titlecolor', '#333333'),
                   fontsize=plot_configs['font.size_title'])
    if xlabel:
      ax.set_xlabel(xlabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])
    if ylabel:
      ax.set_ylabel(ylabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])
    if zlabel:
      ax.set_zlabel(zlabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])

    if show_colorbar:
      cb = fig.colorbar(surf, ax=ax, shrink=0.6, aspect=10, pad=0.1)
      cb.ax.tick_params(colors=theme_settings.get('ytick.color', '#333333'),
                        labelsize=plot_configs['font.size_legend'] - 2)


    if show_plot_on_draw and not should_return_objects:
      plt.show()

    if should_return_objects:
      return fig, ax
    else:
      plt.close(fig)
      return None
    except exceptions.PlottingError:
        raise
    except Exception as e:
        raise exceptions.PlottingError(f"An unexpected error occurred in plot_surface: {e}") from e

  def plot_wireframe(
      self, X, Y, Z,
      title: str = None,
      xlabel: str = None,
      ylabel: str = None,
      zlabel: str = None,
      return_fig_ax: bool = None,
      **kwargs
  ):
    """Plots a 3D wireframe.

    Generates a 3D wireframe plot, applying theme and configuration.

    Args:
      X: 2D array of x-coordinates (e.g., from np.meshgrid).
      Y: 2D array of y-coordinates (e.g., from np.meshgrid).
      Z: 2D array of z-values corresponding to (X, Y).
      title: Optional title for the plot.
      xlabel: Optional label for the x-axis.
      ylabel: Optional label for the y-axis.
      zlabel: Optional label for the z-axis.
      return_fig_ax: Optional. If True, returns (fig, ax). If False, displays.
          If None, uses global config.
      **kwargs: Additional keyword arguments passed to `ax.plot_wireframe()`.
          Useful for `rstride`, `cstride`, `color`, `linewidth`.

    Returns:
      Optionally, a tuple (matplotlib.figure.Figure, matplotlib.axes.Axes3D)
      if `return_fig_ax` is True or if global config 'plot.return_fig_ax'
      is True and `return_fig_ax` is None. Otherwise, returns None.

    Raises:
      exceptions.InvalidPlotDataError: If input data X, Y, Z are unsuitable.
      exceptions.ConfigurationError: If a configuration key is missing.
      exceptions.ThemeNotFoundError: If a theme key is missing.

    Example:
        >>> import numpy as np
        >>> from optiland.plotting import Plotter
        >>> plotter = Plotter()
        >>> x_wire = np.arange(-5, 5, 0.5) # Coarser steps for wireframe
        >>> y_wire = np.arange(-5, 5, 0.5)
        >>> X_wire, Y_wire = np.meshgrid(x_wire, y_wire)
        >>> R_wire = np.sqrt(X_wire**2 + Y_wire**2)
        >>> Z_wire = np.sin(R_wire)
        >>> plotter.plot_wireframe(X_wire, Y_wire, Z_wire, title="3D Wireframe (Sine Wave)",
        ...                        linewidth=0.8)
        >>> plotter.set_theme('dark')
        >>> fig, ax = plotter.plot_wireframe(X_wire, Y_wire, Z_wire, title="Dark Wireframe",
        ...                                  color='cyan', return_fig_ax=True) # Override theme line color
    """
    try:
        X_arr, Y_arr, Z_arr = np.asarray(X), np.asarray(Y), np.asarray(Z)
        if not (X_arr.ndim == 2 and Y_arr.ndim == 2 and Z_arr.ndim == 2):
            raise exceptions.InvalidPlotDataError("X, Y, and Z must be 2D array-like structures.")
        if not (X_arr.shape == Y_arr.shape == Z_arr.shape):
            raise exceptions.InvalidPlotDataError("X, Y, and Z must have the same shape.")
        if X_arr.size == 0:
            raise exceptions.InvalidPlotDataError("Input data X, Y, Z cannot be empty.")

        theme_settings = self.get_current_theme_settings()

        if return_fig_ax is None:
            should_return_objects = self.get_config_value('plot.return_fig_ax')
            show_plot_on_draw = self.get_config_value('plot.show_on_draw')
    else:
      should_return_objects = return_fig_ax
      show_plot_on_draw = not return_fig_ax

    fig = plt.figure(figsize=self.get_config_value('figure.figsize'))
    fig.set_facecolor(theme_settings.get('figure.facecolor', '#FFFFFF'))
    ax = fig.add_subplot(111, projection='3d')

    plot_configs = {
        'font.size_title': self.get_config_value('font.size_title'),
        'font.size_label': self.get_config_value('font.size_label'),
        'font.size_legend': self.get_config_value('font.size_legend'),
    }
    self._apply_theme_and_config_to_ax(ax, theme_settings, plot_configs)

    # Default wireframe color from theme lines.color, allow override
    kwargs.setdefault('color', theme_settings.get('lines.color', '#007ACC'))
    kwargs.setdefault('linewidth', self.get_config_value('lines.linewidth') * 0.75) # Thinner for wireframes


    ax.plot_wireframe(X, Y, Z, **kwargs)

    if title:
      ax.set_title(title, color=theme_settings.get('axes.titlecolor', '#333333'),
                   fontsize=plot_configs['font.size_title'])
    if xlabel:
      ax.set_xlabel(xlabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])
    if ylabel:
      ax.set_ylabel(ylabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])
    if zlabel:
      ax.set_zlabel(zlabel, color=theme_settings.get('axes.labelcolor', '#333333'),
                    fontsize=plot_configs['font.size_label'])

    if show_plot_on_draw and not should_return_objects:
      plt.show()

    if should_return_objects:
      return fig, ax
    else:
      plt.close(fig)
      return None
    except exceptions.PlottingError:
        raise
    except Exception as e:
        raise exceptions.PlottingError(f"An unexpected error occurred in plot_wireframe: {e}") from e

  def plot_scatter(
      self,
      x,
      y,
      title: str = None,
      xlabel: str = None,
      ylabel: str = None,
      legend_label: str = None, # For scatter, legend is more complex if colors/sizes vary
      return_fig_ax: bool = None,
      **kwargs
  ):
    """Plots a scatter graph.

    Generates a scatter plot with the given data, applying current theme and
    configuration settings.

    Args:
      x: Array-like data for the x-axis.
      y: Array-like data for the y-axis.
      title: Optional title for the plot.
      xlabel: Optional label for the x-axis.
      ylabel: Optional label for the y-axis.
      legend_label: Optional label for the scatter points, used if a legend is shown.
                    Note: For scatter plots with varying point colors/sizes,
                    legend handling can be more complex. This basic version assumes
                    a single legend entry for the main data series.
      return_fig_ax: Optional. If True, returns (fig, ax). If False, displays
          the plot and returns None. If None, uses the global
          'plot.return_fig_ax' and 'plot.show_on_draw' config.
      **kwargs: Additional keyword arguments passed to `matplotlib.pyplot.scatter()`.
                Common arguments include `s` for size and `c` or `color` for color.

    Returns:
      Optionally, a tuple (matplotlib.figure.Figure, matplotlib.axes.Axes)
      if `return_fig_ax` is True or if the global config 'plot.return_fig_ax'
      is True and `return_fig_ax` is None. Otherwise, returns None.

    Raises:
      exceptions.InvalidPlotDataError: If input data is unsuitable.
      exceptions.ConfigurationError: If a configuration key is missing.
      exceptions.ThemeNotFoundError: If a theme key is missing.
    """
    try:
        if not (hasattr(x, '__len__') and hasattr(y, '__len__') and len(x) == len(y)):
            raise exceptions.InvalidPlotDataError("x and y must be array-like and have the same length.")
        if len(x) == 0:
            raise exceptions.InvalidPlotDataError("Input data x and y cannot be empty.")

        theme_settings = self.get_current_theme_settings()

        if return_fig_ax is None:
            should_return_objects = self.get_config_value('plot.return_fig_ax')
            show_plot_on_draw = self.get_config_value('plot.show_on_draw')
    else:
      should_return_objects = return_fig_ax
      show_plot_on_draw = not return_fig_ax

    fig, ax = plt.subplots(figsize=self.get_config_value('figure.figsize'))
    fig.set_facecolor(theme_settings.get('figure.facecolor', '#FFFFFF'))

    plot_configs = {
        'font.size_title': self.get_config_value('font.size_title'),
        'font.size_label': self.get_config_value('font.size_label'),
        'font.size_legend': self.get_config_value('font.size_legend'),
    }
    self._apply_theme_and_config_to_ax(ax, theme_settings, plot_configs)

    # Scatter plot specific settings
    # Use 'lines.color' as default marker color, but allow override via kwargs
    marker_color = kwargs.pop('color', kwargs.pop('c', theme_settings.get('lines.color', '#007ACC')))
    marker_size = kwargs.pop('s', self.get_config_value('lines.markersize')**2) # markersize in config is often for line markers, scatter 's' is area.

    ax.scatter(
        x, y, label=legend_label, color=marker_color,
        s=marker_size, **kwargs
    )

    if title:
      ax.set_title(
          title,
          color=theme_settings.get('axes.titlecolor', '#333333'),
          fontsize=self.get_config_value('font.size_title')
      )
    if xlabel:
      ax.set_xlabel(
          xlabel,
          color=theme_settings.get('axes.labelcolor', '#333333'),
          fontsize=self.get_config_value('font.size_label')
      )
    if ylabel:
      ax.set_ylabel(
          ylabel,
          color=theme_settings.get('axes.labelcolor', '#333333'),
          fontsize=self.get_config_value('font.size_label')
      )

    ax.tick_params(axis='x', colors=theme_settings.get('xtick.color', '#333333'))
    ax.tick_params(axis='y', colors=theme_settings.get('ytick.color', '#333333'))

    if legend_label:
      legend = ax.legend(fontsize=self.get_config_value('font.size_legend'))
      legend_text_color = theme_settings.get('legend.labelcolor', theme_settings.get('text.color', '#333333'))
      for text in legend.get_texts():
          text.set_color(legend_text_color)
      if theme_settings.get('legend.facecolor'):
        legend.get_frame().set_facecolor(theme_settings.get('legend.facecolor'))
      if theme_settings.get('legend.edgecolor'):
        legend.get_frame().set_edgecolor(theme_settings.get('legend.edgecolor'))


    if show_plot_on_draw and not should_return_objects:
      plt.show()

    if should_return_objects:
      return fig, ax
    else:
      plt.close(fig)
      return None
    except exceptions.PlottingError:
        raise
    except Exception as e:
        raise exceptions.PlottingError(f"An unexpected error occurred in plot_scatter: {e}") from e
