name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "Hi there! This issue has been automatically marked as stale due to inactivity for **30 days**. If you believe this issue is still relevant, please comment with any updates or additional information. Otherwise, this issue will be closed in **14 days**."
          close-issue-message: "Closing this issue due to prolonged inactivity. If you think this was a mistake, please feel free to reopen the issue."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
